[color-theme]
name = "Dark+"

[color-theme.base]
black = "#212121"
blue = "#569CD6"
cyan = "#9CDCFE"
green = "#4ec9b0"
grey = "#3E3E3E"
magenta = "#C678DD"
orange = "#ce9178"
purple = "#bda1e6"
red = "#f27997"
white = "#CCCCCC"
yellow = "#dcdcaa"

[color-theme.syntax]
attribute = "$cyan"
"builtinAttribute" = "$yellow"
builtinType = "$green"
"boolean" = "$blue"
comment = "#6A9955" # dark green
constant = "$blue" # TODO mid-blue
constructor = ""
"derive" = "$green"
"deriveHelper" = "$yellow"
"decorator" = "$yellow"
embedded = ""
enum = "$green"
enum-member = ""
enumMember = "$blue"
escape = ""
field = ""
"formatSpecifier" = "$blue"
function = "$yellow"
"function.method" = ""
"generic.attribute" = ""
interface = "$green"
keyword = "$blue"
"keyword.control" = ""
label = "$green"
"lifetime" = "$blue"
"macro" = "$blue"
method = "$yellow"
number = "$yellow"
"namespace" = "$green"
"parameter" = "$cyan"
property = "$cyan"
"punctuation.delimiter" = ""
selfKeyword = "$blue"
"selfTypeKeyword" = "$blue"
string = "$orange"
"string.escape" = ""
"string.macro" = ""
"string.template" = ""
struct = "$green"
structure = ""
symbol = ""
tag = ""
"text.reference" = ""
"text.title" = ""
"text.uri" = ""
type = ""
"type.builtin" = ""
typeAlias = "$green"
"typeParameter" = "$cyan"
variable = "$cyan"
"variable.other.member" = "$cyan"

[color-theme.ui]
"activity.background" = "#303031"
"activity.current" = ""
"completion.background" = "#1e1e1e"
"completion.current" = ""
"editor.background" = "#1e1e1e"
"editor.caret" = ""
"editor.current_line" = "#FFFFFF11"
"editor.dim" = "#858585"
"editor.focus" = "#cccccc"
"editor.foreground" = "#d4d4d4"
"editor.link" = "#3794ff"
"editor.selection" = "#264f78"
"error_lens.error.background" = ""
"error_lens.error.foreground" = ""
"error_lens.other.background" = ""
"error_lens.other.foreground" = ""
"error_lens.warning.background" = ""
"error_lens.warning.foreground" = ""
"hover.background" = "#252526"
"inlay_hint.background" = "#4646461a"
"inlay_hint.foreground" = "#969696"
"lapce.active_tab" = "#1e1e1e"
"lapce.border" = "#cccccc33"
"lapce.dropdown_shadow" = ""
"lapce.error" = ""
"lapce.inactive_tab" = "#2d2d2d"
"lapce.scroll_bar" = "#343434"
"lapce.warn" = ""
"markdown.blockquote" = ""
"palette.background" = "#252526"
"palette.current" = "#04395e"
"panel.background" = "#303031"
"panel.current" = "#00000077"
"panel.hovered" = "#FFFFFF11"
"source_control.added" = "#81b88b"
"source_control.modified" = "#e2c08d"
"source_control.removed" = "#c74e39"
"status.background" = "#007acc"
"status.modal.insert" = ""
"status.modal.normal" = ""
"status.modal.terminal" = ""
"status.modal.visual" = ""
"terminal.background" = "#1e1e1e"
"terminal.black" = "#000000"
"terminal.blue" = "#2472c8"
"terminal.bright_black" = "#666666"
"terminal.bright_blue" = "#3b8eea"
"terminal.bright_cyan" = "#29b8db"
"terminal.bright_green" = "#23d18b"
"terminal.bright_magenta" = "#d670d6"
"terminal.bright_red" = "#f14c4c"
"terminal.bright_white" = "#e5e5e5"
"terminal.bright_yellow" = "#f5f543"
"terminal.cursor" = "$white"
"terminal.cyan" = "#11a8cd"
"terminal.foreground" = "$white"
"terminal.green" = "#0dbc79"
"terminal.magenta" = "#bc3fbc"
"terminal.red" = "#cd3131"
"terminal.white" = "$white"
"terminal.yellow" = "#e5e510"