author = "panekj"
description = "Themes based on VS Code default looks"
display-name = "Visual Studio Code"
name = "lapce-vscode-theme"
version = "0.0.0"
color-themes = [
  "Dark+.toml",
  "Light+.toml",
]
